# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestForm():
  def setup_method(self, method):
    chrome_options = Options()
    chrome_options.add_argument("--disable-search-engine-choice-screen")
    self.driver = webdriver.Chrome(options=chrome_options)
    self.vars = {}
 
  def teardown_method(self, method):
    self.driver.quit()
 

 
  def test_test2(self):
    self.driver.get("https://demoqa.com/text-box")
    # Remplir les champs du formulaire
    self.driver.find_element(By.ID, "userName").send_keys("John Doe")
    self.driver.find_element(By.ID, "userEmail").send_keys("john.doe@example.com")
    self.driver.find_element(By.ID, "currentAddress").send_keys("123 Rue de Paris")
    self.driver.find_element(By.ID, "permanentAddress").send_keys("456 Rue de Lyon")

    # Soumettre le formulaire
    self.driver.find_element(By.ID, "submit").click()

    # Vérifier les valeurs saisies
    assert "John Doe" in self.driver.find_element(By.ID, "name").text
    assert "john.doe@example.com" in self.driver.find_element(By.ID, "email").text
    assert "123 Rue de Paris" in self.driver.find_element(By.ID, "output").text
    assert "456 Rue de Lyon" in self.driver.find_element(By.ID, "output").text
